name: Build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
    
      #Remove if not needed, clone the LA project and get seer
      - name: Clone LA Repository
        run: git clone https://github.com/GiR-Zippo/LightAmp.git

      - name: tte
        run: ls
      
      - name: Identify files to invalidate
        run: |
          $Folder1 = Get-childitem "BardMusicPlayer.Seer" \
          $Folder2 = Get-childitem  "LightAmp/BardMusicPlayer.Seer" \
          Compare-Object $Folder1 $Folder2 -Property Name, Length > changed.txt


      - name: cat 
        run: cat changed.txt

