name: Build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
    
      #Remove if not needed, clone the LA project and get seer
      - name: Clone LA Repository
        run: git clone https://github.com/GiR-Zippo/LightAmp.git
      
      - name: Identify files to invalidate
        uses: docker://fmichonneau/ga-compare-folders:latest
        env:
          FOLDER_1: BardMusicPlayer.Seer/
          FOLDER_2: LightAmp/BardMusicPlayer.Seer/
          OUTPUT: changed_files.txt
          ADD_ROOTS: true

      - name: cat 
        run: cat changed_files.txt

