name: Build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
    
      #Remove if not needed, clone the LA project and get seer
      - name: Clone LA Repository
        run: git clone https://github.com/GiR-Zippo/LightAmp.git

      - name: Compare SEER Folder
        run: |
          $Folder1 = Get-childitem ".\BardMusicPlayer.Seer"
          $Folder2 = Get-childitem  ".\LightAmp/BardMusicPlayer.Seer"
          Compare-Object $Folder1 $Folder2 -Property Name, Length > changed.txt

      - name: Check for output
        id: "compare"
        run: if (Get-Content .\changed.txt){echo "CHANGED=false" >> $env:GITHUB_OUTPUT}else{echo "CHANGED=true" >> $env:GITHUB_OUTPUT}


      - if: steps.compare.outputs.CHANGED  == 'true'
        name: IF
        run: echo ":)"

      - if: steps.compare.outputs.CHANGED  == 'false'
        name: IF NOT
        run: echo ":("

      - name: cat 
        run: cat changed.txt

